#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GeeseDisturberProject.Resource", IsApplication=true)]

namespace GeeseDisturberProject
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::GeeseDisturberProject.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::GeeseDisturberProject.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::GeeseDisturberProject.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::GeeseDisturberProject.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int remotecontrol2e = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int Back = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int Camera = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int Control = 2131034126;
			
			// aapt resource value: 0x7f050016
			public const int ListView = 2131034134;
			
			// aapt resource value: 0x7f050010
			public const int Settings = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int StreamSettings = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int WebView = 2131034112;
			
			// aapt resource value: 0x7f050013
			public const int btnAdd = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int btnDelete = 2131034133;
			
			// aapt resource value: 0x7f050009
			public const int btnDown = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int btnEdit = 2131034132;
			
			// aapt resource value: 0x7f050007
			public const int btnLeft = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int btnRight = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int btnUp = 2131034117;
			
			// aapt resource value: 0x7f050011
			public const int edtAddress = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int edtPort = 2131034130;
			
			// aapt resource value: 0x7f050004
			public const int space1 = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int space2 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int space3 = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int space4 = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int textView1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textView2 = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int webView1 = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CameraActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CameraActivitySettings = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ControlGMaps = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ControlMenu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ControlsPadActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int list_view_dataTemplate = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainMenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainSettings = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
